/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  pisuw
 * Created: 5-giu-2017
 * I dati per la connessione ai database sono i seguenti:
 *      user:Pisu
 *      password:amm2017
 */

CREATE TABLE tipiPost (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR(32)
);

CREATE TABLE tipiUtenti (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR(14)
);


CREATE TABLE utenti (
             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             nome VARCHAR(128) NOT NULL,
             cognome VARCHAR(128),
             data_nascita VARCHAR(256),
             presentazione VARCHAR(1024),
             img VARCHAR(256),
             mail VARCHAR(256) NOT NULL,
             password VARCHAR(256) NOT NULL,
             tipo_utente INTEGER NOT NULL,
             FOREIGN KEY (tipo_utente) REFERENCES tipiUtenti(id) 
);




CREATE TABLE gruppi(
             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             nome VARCHAR(128) NOT NULL,
             creatore INTEGER NOT NULL,
             FOREIGN KEY (creatore) REFERENCES utenti(id) ON DELETE CASCADE 
);


CREATE TABLE posts (
             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             id_utente INTEGER NOT NULL,
             FOREIGN KEY (id_utente) REFERENCES utenti(id) ON DELETE CASCADE,
             id_gruppo INTEGER,
             FOREIGN KEY (id_gruppo) REFERENCES gruppi(id) ON DELETE CASCADE ,
             contenuto VARCHAR(1024) NOT NULL,
             tipo_post INTEGER NOT NULL, 
             FOREIGN KEY (tipo_post) REFERENCES tipiPost(id)               
);


/*tabella della relazione fra utenti e gruppi con chiave primaria le chiavi esterne di utenti e gruppi*/
CREATE TABLE membri(
             id_gruppo INTEGER NOT NULL,
             id_utente INTEGER NOT NULL,
             PRIMARY KEY (id_gruppo, id_utente),
             FOREIGN KEY (id_gruppo) REFERENCES gruppi(id) ON DELETE CASCADE,
             FOREIGN KEY (id_utente) REFERENCES utenti(id) ON DELETE CASCADE
);

/*tabella amicizie--------------------------------------------------------------------------------------------*/
/*le amicizie devono essere reciproche*/
CREATE TABLE amicizie(
             id_utente INTEGER NOT NULL ,
             id_amico INTEGER NOT NULL ,
             PRIMARY KEY (id_utente, id_amico),
             FOREIGN KEY (id_utente) REFERENCES utenti(id) ON DELETE CASCADE,
             FOREIGN KEY (id_amico) REFERENCES utenti(id) ON DELETE CASCADE 
);


/*Popolamento tabella tipoPost*/
INSERT INTO tipiPost (id, nome)
VALUES (default, 'TEXT');

INSERT INTO tipiPost (id, nome)
VALUES (default, 'IMAGE');

INSERT INTO tipiPost (id, nome)
VALUES (default, 'LINK');


/*popolamento tabella tipi utenti*/
INSERT INTO tipiUtenti (id, nome)
VALUES (default, 'AMMINISTRATORE');

INSERT INTO tipiUtenti (id, nome)
VALUES (default, 'UTENTE');

/*Popolo la tabella utenti*/
INSERT INTO utenti(id, nome, cognome, img, mail, password, tipo_utente)
VALUES(default,'Rufy', 'Monkey D.','/img/167654_149070858481920_148641161858223_267054_8188355_n-150x150.jpg','Rufy@gmail.com','1234',1);

INSERT INTO utenti(id, nome, cognome, img, mail, password, tipo_utente)
VALUES(default,'Goku', 'Son','/img/180863_148926285163044_148641161858223_266218_7815533_n-150x150.jpg','Goku@gmail.com','1234',2);
 
INSERT INTO utenti(id, nome, cognome, img, mail, password, tipo_utente)
VALUES(default,'Stormtrooper', '2187','/img/180863_148926285163044_148641161858223_266218_7815533_n-150x150.jpg','Stormtrooper2187@gmail.com','1234',2);
 
INSERT INTO utenti(id, nome, cognome, img, mail, password, tipo_utente)
VALUES(default,'Stormtrooper', '7812','/img/5f608695abe0aca21adb54ea329a63c7.jpg','Stormtrooper7812@gmail.com','1234',2);

/*popolo la tabella amicizie*/
INSERT INTO amicizie (id_utente, id_amico)
VALUES (1,2);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (2,1);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (1,3);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (3,1);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (1,4);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (4,1);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (2,3);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (3,2);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (4,2);

INSERT INTO amicizie (id_utente, id_amico)
VALUES (2,4);


/*Popolo la tabella di gruppi*/
INSERT INTO gruppi (id, nome, creatore)
values (default, 'One pice', 1);

INSERT INTO gruppi (id, nome, creatore)
values (default, 'Dragon Ball', 3);

INSERT INTO membri (id_gruppo, id_utente)
VALUES (1,1);

INSERT INTO membri (id_gruppo, id_utente)
VALUES (1,3);

INSERT INTO membri (id_gruppo, id_utente)
VALUES (2,2);

INSERT INTO membri (id_gruppo, id_utente)
VALUES (2,4);

/*creo dei post di tipi diversi di gruppi e non*/
INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 1, 1,'Diventerò il Re dei Pirati!', 1);

INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 4, 2,'www.starwars.com', 3);

INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 1, NULL,'Diventerò il Re dei Pirati!', 1);

INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 2, NULL,'/img/imgsazio.gif', 2);

INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 3, NULL,'www.nerdbook.com/login.html', 3);





