/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  pisuw
 * Created: 5-giu-2017
 * I dati per la connessione ai database sono i seguenti:
 *      user:Pisu
 *      password:amm2017
 */

CREATE TABLE tipiPost (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR(32)
);

CREATE TABLE utenti (
             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             nome VARCHAR(128) NOT NULL,
             cognome VARCHAR(128),
             data_nascita VARCHAR(256),
             presentazione VARCHAR(1024),
             img VARCHAR(256),
             mail VARCHAR(256) NOT NULL,
             password VARCHAR(256) NOT NULL
);




CREATE TABLE gruppi(
             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             nome VARCHAR(128) NOT NULL,
             creatore INTEGER NOT NULL,
             FOREIGN KEY (creatore) REFERENCES utenti(id)
);


CREATE TABLE posts (
             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             id_utente INTEGER NOT NULL,
             FOREIGN KEY (id_utente) REFERENCES utenti(id),
             id_gruppo INTEGER,
             FOREIGN KEY (id_gruppo) REFERENCES gruppi(id),
             contenuto VARCHAR(1024) NOT NULL,
             tipo_post INTEGER NOT NULL,
             FOREIGN KEY (tipo_post) REFERENCES tipiPost(id)             
);


/*tabella della relazione fra utenti e gruppi con chiave primaria le chiavi esterne di utenti e gruppi*/
CREATE TABLE membri(
             id_gruppo INTEGER NOT NULL,
             id_utente INTEGER NOT NULL,
             PRIMARY KEY (id_gruppo, id_utente),
             FOREIGN KEY (id_gruppo) REFERENCES gruppi(id),
             FOREIGN KEY (id_utente) REFERENCES utenti(id)
);

/*tabella amicizie--------------------------------------------------------------------------------------------*/
/*le amicizie devono essere reciproche*/
CREATE TABLE amicizie(
             id_utente INTEGER NOT NULL ,
             id_amico INTEGER NOT NULL ,
             PRIMARY KEY (id_utente, id_amico),
             FOREIGN KEY (id_utente) REFERENCES utenti(id),
             FOREIGN KEY (id_amico) REFERENCES utenti(id)
);

/*Popolo la tabella utenti*/
INSERT INTO utenti(id, nome, cognome, img, mail, password)
VALUES(default,'Rufy', 'Monkey D.','/img/167654_149070858481920_148641161858223_267054_8188355_n-150x150.jpg','Rufy@gmail.com','1234');
/* ----------------------------------------popolare gli altri campi---------------------------------------*/
INSERT INTO utenti(id, nome, cognome, img, mail, password)
VALUES(default,'Rufy', 'Monkey D.','/img/167654_149070858481920_148641161858223_267054_8188355_n-150x150.jpg','Rufy@gmail.com','1234');
 
INSERT INTO utenti(id, nome, cognome, img, mail, password)
VALUES(default,'Rufy', 'Monkey D.','/img/167654_149070858481920_148641161858223_267054_8188355_n-150x150.jpg','Rufy@gmail.com','1234');
 
INSERT INTO utenti(id, nome, cognome, img, mail, password)
VALUES(default,'Rufy', 'Monkey D.','/img/167654_149070858481920_148641161858223_267054_8188355_n-150x150.jpg','Rufy@gmail.com','1234');
       
/*Popolamento tabella tipoPost*/
INSERT INTO tipiPost (id, nome)
VALUES (default, 'TEXT');

INSERT INTO tipiPost (id, nome)
VALUES (default, 'IMAGE');

INSERT INTO tipiPost (id, nome)
VALUES (default, 'LINK');

/*Popolo la tabella di gruppi*/
INSERT INTO gruppi (id, nome, creatore)
values (default, 'One pice', 1);

INSERT INTO gruppi (id, nome, creatore)
values (default, 'Dragon Ball', 3);

/*creo dei post di tipi diversi di gruppi e non*/
INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 1, 1,'Diventerò il Re dei Pirati!', 1);

INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 1, NULL,'Diventerò il Re dei Pirati!', 1);

INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 2, NULL,'/img/imgsazio.gif', 2);

INSERT INTO posts (id, id_utente, id_gruppo, contenuto, tipo_post )
VALUES (default, 3, NULL,'www.nerdbook.com/login.html', 3);





